input_dir: "/ssd0/shenzhen/Datasets/depth/workzone_segm/pittsburgh"

# T2I Parameters
cfg: 10

# NOTE: set this to true!
center_crop: true

inference_mode: driving

# Debugging
max_images: 1  # Set to a number for debugging, otherwise leave null if unlimited