
input_dir: "/home/shenzhen/Datasets/dataset_with_garment_bigface_start_100_end_200"
max_images: null # NOTE: return to null for full dataset

# NOTE: set this one to false
upper_crop: false # upper_crop: false